name: Hands-on 3
on: pull_request
jobs:
  python_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
      - name: Run unit test
        run: python test_plus.py -v
